//
//  RM_Entity.swift
//  RM_
//
//  Created by Oleh Kulykov on 22/04/16.
//  Copyright © 2016 Oleh Kulykov. All rights reserved.
//


import Foundation
import CoreData


/**
Public protocol for all entities.
This protocol contains all public getters/variables and functions for interacting with the actual entity object.
*/
public protocol RM_EntityType {

	/**
	Placeholder for the public entity protocol.
	DAL's expects and operates with this type, so define this type within final entity implementation.
	*/
	associatedtype PublicType
}


/// Autogenerated base `RM_Entity` class.
open class RM_Entity: NSManagedObject {

}

