//
//  RM_User.swift
//  RM_
//
//  Created by Oleh Kulykov on 22/04/16.
//  Copyright © 2016 Oleh Kulykov. All rights reserved.
//


import Foundation
import CoreData


/**
Public user protocol.
Use this protocol with readonly/immutable DAL.
*/
protocol RM_UserType {

	/**
	User identifier string. 
	Since this variable present in `RM_Entity`, we just define get variable.
	*/
	var oId: String { get }

	
	/**
	Name of the user.
	Since this variable present in `RM_User`, we just define get variable.
	*/
	var name: String { get }


	/**
	Upper case version of the name.
	This is computed variable and we need to provide implementation within final actual `RM_User` class or extension.
	*/
	var upperCaseName: String { get }
}


/// Autogenerated base `RM_User` class.
final class RM_User: RM_Entity {

}


extension RM_User: RM_UserType, RM_EntityType {

	/// Define public protocol of the internal/actual `RM_User` class.
	typealias PublicType = RM_UserType


	/**
	Upper case version of the name.
	*/
	var upperCaseName: String {
		return name.uppercaseString
	}

}
